### ISSUE TITLE
Optional cache-busting

### ISSUE THREAD

**Issue by stoff** [isitedesign/Phoenix#125]
It's come up a few times now that cache busting is not a good fit for CMS platforms that exercise some degree of control over CSS and other assets (think Drupal or Wordpress). In order to better accommodate these or similar systems, we should make cache-busting optional.

I've created [feature/optional-cache-busting](https://github.com/isitedesign/Phoenix/tree/feature/optional-cache-busting) demonstrating a possible approach.

**Comment by kamsar** [comment]
Seems legit. BTW looks like you might need to set email on your gitconfig as that commit is from 'unknown'

**Comment by ajmueller** [comment]
Great idea @stoff.  Could you make a PR for this?  It seems simple enough to review quickly this week and get into the Friday release.

**Comment by stoff** [comment]
Per discussion with @ajmueller I've one other piece to add: remove the cache busting from the img/content directory, since those items should be managed by a CMS.  I'll add a commit for that and make a PR in the next day or so.

**Comment by stoff** [comment]
Added filter for /img/content and created PR #126

**Comment by ajmueller** [comment]
Closing since #126 is merged.
