### ISSUE TITLE
Removing PHP/Server dependency for templates

### ISSUE THREAD

**Issue by chadian** [isitedesign/Phoenix#89]
Commonly our templates depend on PHP to be viewed, but not everyone is running PHP in their stack.

An easy option I can think of is to include a php2html gulp build process. We would then have files that would be deployable anywhere, and not rely on a server either since no server-side processing is required. Clients could open static html on their own machines (or with apps iPhones, iPads, Android, etc).

What we gain is the same end result except of what gets sent to the browser, with all the same benefits of using PHP behind the scenes for includes, variables, etc, for easy templates.

The one negative aspect I can think of is if we use any get / post params for mimicking server-side routing/ajax/forms.

Another negative is that it's not necessarily true that all users of Phoenix use PHP for templating, and this process would add an opinion about using PHP for templating.

Thoughts anyone?

**Comment by ajmueller** [comment]
Closing this based on above discussion.
